version: '3.8'
services:
  dashboard:
    build:
      context: .
    container_name: productionpal_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./productionpal_dashboard.log:/app/productionpal_dashboard.log
    command: streamlit run app/dashboard.py --server.port=8501 --server.address=0.0.0.0

  sensor_mocker:
    build:
      context: .
    container_name: productionpal_sensor
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./productionpal_sensor.log:/app/productionpal_sensor.log
    command: python sensor_mocker.py

  mlflow:
    build:
      context: .
    container_name: productionpal_mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
    command: mlflow ui --backend-store-uri mlruns --host 0.0.0.0 --port 5000

  gateway:
    build:
      context: .
    container_name: productionpal_gateway
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python app/gateway.py
